[font]
size = 12

[font.normal]
family = "CaskaydiaMono Nerd Font"
style = "Regular"

[general]
import = [
    "catppuccin/mocha.toml",
]

[keyboard]
bindings = [
    {key = "Q", mode = "Vi", action = "ToggleViMode" },
]

[cursor]
style = {shape = "Beam"}
