#!/bin/sh
# shellcheck disable=SC1090,SC3043

# perl to remove any trailing new line
# Convert to base 64 for OSC 52 to copy to clipboard. Works over ssh
alias copy='perl -pe "chomp if eof" | base64 -w 0 | xargs printf "\033]52;c;%s\a"'

# shellcheck disable=SC2142
alias gitpb="git branch -vv | awk '\$3 \$4 ~ /:gone]$/ { print \$1 }' | xargs -n 1 git branch -D" # Remove branches that have been deleted on upstream
alias sd='shutdown -P 0'
alias g='git'
alias gl='git log --oneline'
alias gc='git checkout'
alias gitl='gl'
alias lg='lazygit'

# git reword reuse
alias grr='git commit --amend --edit -F .git/COMMIT_EDITMSG'
alias gitrr='grr'

# git reword
alias gr='git commit --amend'
alias gitr='gr'

{ command -v gf && { unalias gf || unset gf; }; } >/dev/null 2>&1
alias gf='git fetch --all'

alias rg='\rg -M 250'

_get_shell() {
    if [ -n "$ZSH_VERSION" ]; then
        echo "zsh"
    elif [ -n "$BASH_VERSION" ]; then
        echo "bash"
    else
        echo "sh"
    fi
}

# C define search
rgd() {
    local search_term="$1"
    shift
    rg "#define\s+$search_term" "$@"
}

re_source() {
    . "$HOME/.$(_get_shell)rc"
}

[ -e "$HOME/.config/.local_aliases" ] && . "$HOME/.config/.local_aliases"
