#!/bin/sh

# If not running interactively, don't do anything
case $- in
*i*) ;;
*) return 1 ;;
esac

[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

export EDITOR="nvim"
export MANPAGER="nvim +Man!"

PATH="$HOME/bin/:$HOME/scripts/:$PATH"
