#!/bin/sh

# If not running interactively, don't do anything
case $- in
*i*) ;;
*) return 1 ;;
esac

[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

export EDITOR="nvim"
export MANPATH="$HOME/share/man:$MANPATH"
export MANPAGER="nvim +Man!"

PATH="$HOME/.cargo/bin/:$HOME/bin/:$HOME/scripts/:$HOME/.local/bin:$PATH"

[ -e "$HOME/.config/.localrc" ] && . "$HOME/.config/.localrc"

if [ -e "$HOME/.config/.sh_aliases" ]; then
	. "$HOME/.config/.sh_aliases"
fi

[ -e "$HOME/.cargo/env" ] && . "$HOME/.cargo/env"
true
